version: "3"

services:
  postgres:
    image: postgres:10-alpine
    container_name: ad-scraping-postgres
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - ad-postgres-data:/var/lib/postgresql/data
    ports:
      - "5555:5432"
  redis:
    image: redis:alpine
    container_name: ad-scraping-redis
    ports:
      - "6379:6379"
    volumes:
      - ad-redis-cache:/var/lib/redis/data
  web:
    build: .
    image: ad-scraping-app
    command: sh -c 'rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0 -p 3000'
    container_name: ad-scraping-app
    ports:
      - "3000:3000"
    volumes:
      - .:/myapp:cached
      - /myapp/log
      - /myapp/.git
      - /myapp/tmp
      - ad-bundle:/usr/local/bundle
    tty: true
    stdin_open: true
    restart: always
    depends_on:
      - postgres
      - redis
  # webpack:
  #   build: .
  #   image: ad-scraping-webpack
  #   command: sh -c './bin/webpack-dev-server'
  #   container_name: ad-scraping-webpack
  #   ports:
  #     - "3035:3035"
  #   volumes:
  #     - .:/myapp:cached
  #   tty: false
  #   stdin_open: false
  #   depends_on:
  #     - web
  worker:
    build: .
    image: ad-scraping-worker
    command: bundle exec sidekiq -C config/sidekiq.yml
    container_name: ad-scraping-worker
    volumes:
      - .:/myapp
    depends_on:
      - postgres
      - redis

volumes:
  ad-bundle:
    driver: local
  ad-postgres-data:
    driver: local
  ad-redis-cache:
    driver: local
